### ISSUE TITLE
Версии SentencePiece и FairSeq

### ISSUE THREAD

**Issue by EvgeniaKomleva** [dialogue-evaluation/RuSimpleSentEval#1]
Спасибо за вашу работу! 

Подскажите пожалуйста какие версии SentencePiece и FairSeq вы используете в базовом решении

**Comment by Andoree** [comment]
Добрый день!
SentencePiece версии 0.1.95, FairSeq версии 0.10.2

**Comment by EvgeniaKomleva** [comment]
Я пытаюсь запустить базовое решение с вышеуказанными версиями, но появляется такая ошибка: 

![image](https://user-images.githubusercontent.com/36705500/109924212-ffb49a80-7cd0-11eb-9f27-286d6bb308cf.png)

Исходя из https://github.com/pytorch/fairseq/issues/3169,нужно использовать какую то другую версию. Я пробовала использовать предпоследнюю, но там тоже были какие то ошибки, связанные с несовместимостью. 

Подскажите пожалуйста, как можно обойти проблему?

**Comment by tutubalinaev** [comment]
Добрый день! Все зависит от вашего виртуального окружения. Рекомендую спросить в чате участников соревнования (в tg), у нас подобной ошибки не было.

**Comment by EvgeniaKomleva** [comment]
Спасибо, хорошего дня!
